name: OSS 
on:
  push: 
    branches: 
      - master
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Disable ACTIONS_ALLOW_UNSECURE_COMMANDS env
        run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV
      - uses: actions/checkout@master
      - uses: manyuanrong/setup-ossutil@v1.0
        with:
          endpoint: "oss-cn-chengdu.aliyuncs.com"
          access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
          sts-token: ""
      - run: ossutil cp -rf ./ oss://agou-links/
      
